version: "3.9"

services:
  springboot:
    image: 445971788373.dkr.ecr.ap-northeast-2.amazonaws.com/final-7team-springboot:latest
    container_name: springboot
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  fastapi:
    image: 445971788373.dkr.ecr.ap-northeast-2.amazonaws.com/final-7team-fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  react:
    image: 445971788373.dkr.ecr.ap-northeast-2.amazonaws.com/final-7team-react:latest
    container_name: react
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: 445971788373.dkr.ecr.ap-northeast-2.amazonaws.com/final-7team-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - springboot
      - fastapi
      - react
      - redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
