name: Backend CI/CD to AWS ECR

on:
  # main merge 시 CD + dev PR 시 CI 동작하도록 추가
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle Wrapper 실행 권한 부여 (추가)
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: springboot

      # 3. Spotless 코드 스타일 검사 
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        working-directory: springboot

      # 4. Gradle 빌드 & 테스트 
      - name: Run Gradle Build & Test
        run: ./gradlew build
        working-directory: springboot

      # 5. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 6. ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 7. 변경된 디렉토리 감지 (SpringBoot / FastAPI / Nginx)
      - name: Detect changed directories
        id: changes
        run: |
          echo "springboot=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^springboot/' || true)" >> $GITHUB_ENV
          echo "fastapi=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^fastapi/' || true)" >> $GITHUB_ENV
          echo "nginx=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^nginx/' || true)" >> $GITHUB_ENV

      # 8. SpringBoot 이미지 빌드 & 푸시
      - name: Build & Push SpringBoot
        if: env.springboot != ''
        run: |
          echo "SpringBoot 변경 감지 → 이미지 빌드 & 푸시"
          docker build -t ${{ secrets.ECR_REGISTRY }}/final-7team-springboot:latest ./springboot
          docker push ${{ secrets.ECR_REGISTRY }}/final-7team-springboot:latest

      # 9. FastAPI 이미지 빌드 & 푸시
      - name: Build & Push FastAPI
        if: env.fastapi != ''
        run: |
          echo "FastAPI 변경 감지 → 이미지 빌드 & 푸시"
          docker build -t ${{ secrets.ECR_REGISTRY }}/final-7team-fastapi:latest ./fastapi
          docker push ${{ secrets.ECR_REGISTRY }}/final-7team-fastapi:latest

      # 10. Nginx 이미지 빌드 & 푸시
      - name: Build & Push Nginx
        if: env.nginx != ''
        run: |
          echo "Nginx 변경 감지 → 이미지 빌드 & 푸시"
          docker build -t ${{ secrets.ECR_REGISTRY }}/final-7team-nginx:latest ./nginx
          docker push ${{ secrets.ECR_REGISTRY }}/final-7team-nginx:latest

  # main 브랜치에 merge될 때만 EC2 자동 배포
  deploy-to-ec2:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-push-backend

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose pull
            docker-compose up -d
            docker image prune -f
